questions =  [
    {"id": 0, "question": "You would like a sexual relationship in which you humiliate your partner sexually.", "effects": {"right": 1}},
    {"id": 1, "question": "Sexual acts involving feet arouse you.", "effects": {"right": 1}},
    {"id": 2, "question": "You enjoy sexual themes based around racial stereotypes/racism.", "effects": {"right": 1}},
    {"id": 3, "question": "Directing sexist phrases at your partner during sex arouses you.", "effects": {"right": 1}},
    {"id": 4, "question": "You find it arousing to have sex with a partner that is unconscious / asleep.", "effects": {"right": 1}},
    {"id": 5, "question": "You enjoy sexual intercourse that is for the purpose of procreation.", "effects": {"right": 1}},
    {"id": 6, "question": "Your partner roleplaying as an age significantly younger than their actual age is arousing to you.", "effects": {"right": 1}},
    {"id": 7, "question": "You find muscular men attractive.", "effects": {"right": 1}},
    {"id": 8, "question": "You find muscular women attractive.", "effects": {"right": -1}},
    {"id": 9, "question": "Being gagged by your partner is arousing.", "effects": {"right": -1}},
    {"id": 10, "question": "You enjoy giving your partner oral sex.", "effects": {"right": -1}},
    {"id": 11, "question": "You find anal toys hot.", "effects": {"right": -1}},
    {"id": 12, "question": "Pain is arousing to you.", "effects": {"right": -1}},
    {"id": 13, "question": "You enjoy vanilla sex.", "effects": {"right": -1}},
    {"id": 14, "question": "Being pegged/pegging your partner is something you would enjoy.", "effects": {"right": -1}},
    {"id": 15, "question": "You enjoy sexually disciplining your partner into obeying certain orders sexually.", "effects": {"auth": 1}},
    {"id": 16, "question": "Handcuffing your partner/being handcuffed is sexually arousing.", "effects": {"auth": 1}},
    {"id": 17, "question": "Being restricted via rope, chains, or other means is something of sexual interest to you.", "effects": {"auth": 1}},
    {"id": 18, "question": "Treating your partner as though they were your slave / vice versa is arousing.", "effects": {"auth": 1}},
    {"id": 19, "question": "Restricting what your partner can say or do / vice versa is arousing.", "effects": {"auth": 1}},
    {"id": 20, "question": "You sexually enjoy being kept/keeping others in a cage.", "effects": {"auth": 1}},
    {"id": 21, "question": "Having your sexual actions dictated by your partner is arousing to you.", "effects": {"auth": 1}},
    {"id": 22, "question": "You are sexually aroused by the concept of hypnotism/mind control being used in a sexual context.", "effects": {"auth": 1}},
    {"id": 23, "question": "Talking back to a dominant partner is something you would do in a sexual setting.", "effects": {"auth": -1}},
    {"id": 24, "question": "You dislike the idea of non-consensual sex.", "effects": {"auth": -1}},
    {"id": 25, "question": "Having sex in a tribal area would be more arousing than in a traditional setting.", "effects": {"auth": -1}},
    {"id": 26, "question": "You dislike being humiliated during sex.", "effects": {"auth": -1}},
    {"id": 27, "question": "You would dislike eating someone / being eaten under sexual contexts (vore).", "effects": {"auth": -1}},
    {"id": 28, "question": "You would dislike your partner stepping on you to show dominance.", "effects": {"auth": -1}},
    {"id": 29, "question": "You would not be aroused by your partner harming you during sexual activities.", "effects": {"auth": -1}},
    {"id": 30, "question": "You find it more sexually arousing if the submissive is larger than the dominant.", "effects": {"prog": 1}},
    {"id": 31, "question": "Being penetrated by 3+ things is arousing to you.", "effects": {"prog": 1}},
    {"id": 32, "question": "Zoophilia is arousing to you.", "effects": {"prog": 1}},
    {"id": 33, "question": "You enjoy CBT.", "effects": {"prog": 1}},
    {"id": 34, "question": "You find small cocks attractive.", "effects": {"prog": 1}},
    {"id": 35, "question": "Losing a limb would feel sexually fulfilling to you.", "effects": {"prog": 1}},
    {"id": 36, "question": "A sexual partner made from a type of slime or gel would be arousing.", "effects": {"prog": 1}},
    {"id": 37, "question": "Necrophilia is something that you find sexually attractive.", "effects": {"prog": 1}},
    {"id": 38, "question": "You are heterosexual.", "effects": {"prog": -1}},
    {"id": 39, "question": "You would not have sex with someone who is transgender.", "effects": {"prog": -1}},
    {"id": 40, "question": "You would not have sex outside of marriage.", "effects": {"prog": -1}},
    {"id": 41, "question": "You dislike being dominated by a women during sex.", "effects": {"prog": -1}},
    {"id": 42, "question": "You are not aroused by fictional creatures (pokemon, dragons, etc).", "effects": {"prog": -1}},
    {"id": 43, "question": "Incest is not a sexual act you are interested in.", "effects": {"prog": -1}},
    {"id": 44, "question": "Having others watch you have sex would make you uncomfortable.", "effects": {"prog": -1}},
    {"id": 45, "question": "You find lingerie arousing.", "effects": {"prog": -1}}
];